'use client';

import Link from 'next/link';
import Image from 'next/image';
import { useEffect, useMemo, useRef, useState } from 'react';
import {
  Sparkles,
  Plus,
  Mic,
  ChevronDown,
  AudioLines,
  AudioWaveform,
  ArrowUp,
  Headphones,
  Heart,
  Check,
} from 'lucide-react';
import { fetchPublicPacks, STATIC_PACK_FALLBACK, type CreditPack } from '@/lib/api';
import { isLikelyIndia } from '@/components/pricing/CurrencyToggle';

const SUPPORT_EMAIL = 'support@blinkugc.com';

/* ============================================================
   Blink UGC — landing page
   Faithfully ported from the design mock, rebranded:
     • UGCForge  → Blink UGC
     • Seedance  → Kling 3.0 Pro
   The hero video wall and showcase cards render the real
   template videos hosted on Cloudinary — the same source the
   iOS app and API use.
============================================================ */

// Real template videos used by the Blink UGC app (same Cloudinary
// account that powers /api/ugc/featured). Hardcoded here so the
// landing renders instantly even before the API responds.
const CLOUDINARY_BASE = 'https://res.cloudinary.com/dgx0o3xfx/video/upload';

// Raw template ids: `<version>/<public_id>` — keep one entry per
// distinct creator so the wall feels varied.
const TEMPLATE_SOURCES: { id: string; label: string }[] = [
  // Swapped clothing → new fashion clip
  { id: 'v1780167073/0d7e39d2-02e8-46b8-955c-efbe255642c0_ycd9fe', label: 'Fashion' },
  { id: 'v1780169471/e68ebdc8-0a31-42a8-9c0a-f89a8917ef7c_snxjsd', label: 'Skincare' },
  // Swapped lipgloss → new beauty clip
  { id: 'v1780169462/b1f2f873-b489-4b82-b9d5-c8607ccceac2_naofgc', label: 'Beauty' },
  // Swapped jewellery_1 → new jewellery clip
  { id: 'v1780167075/cd1b7b3e-4e9d-46ae-84f3-040a85eee8ca_1_yhiw9w', label: 'Jewellery' },
  { id: 'v1780166202/f0eeb973-9fec-4ac3-949a-43eef1379277_2_mlt9hy', label: 'Evening' },
  { id: 'v1779194268/gym_wjiimf', label: 'Fitness' },
];

// https://res.cloudinary.com/dgx0o3xfx/video/upload/v1780169471/e68ebdc8-0a31-42a8-9c0a-f89a8917ef7c_snxjsd.mp4
// https://res.cloudinary.com/dgx0o3xfx/video/upload/v1780169462/b1f2f873-b489-4b82-b9d5-c8607ccceac2_naofgc.mp4

// Cloudinary URL-based transforms. `f_auto` picks WebM/HEVC/MP4 per
// browser, `q_auto` compresses aggressively, `w_<n>` shrinks to the
// tile size, `so_0` makes the poster the first keyframe.
function cldVideo(id: string, w: number) {
  return `${CLOUDINARY_BASE}/f_auto,q_auto,vc_auto,w_${w}/${id}.mp4`;
}
function cldPoster(id: string, w: number) {
  return `${CLOUDINARY_BASE}/so_0,f_auto,q_auto,w_${w}/${id}.jpg`;
}

// Tile-sized (small) and card-sized (bigger) variants — both are
// way smaller than the source MP4s and cache hard on the Cloudinary
// CDN so subsequent tiles using the same id are instant.
const TILE_VIDEOS = TEMPLATE_SOURCES.map((s) => ({
  src: cldVideo(s.id, 360),
  poster: cldPoster(s.id, 360),
  label: s.label,
}));
const CARD_VIDEOS = TEMPLATE_SOURCES.map((s) => ({
  src: cldVideo(s.id, 720),
  poster: cldPoster(s.id, 720),
  label: s.label,
}));

// Hand-picked "best of" videos featured in the Showcase section under
// the "One amazing video is all it takes to sell." headline. These are
// full UGC outputs (already captioned where appropriate) rather than the
// template-source clips reused elsewhere on the page.
//
// Mixed-source: the first and third tiles point at Cloudinary; the
// middle tile is currently served from /public/showcase/ pending
// upload to Cloudinary. Once the local middle file is uploaded, swap
// its entry back to the cldVideo/cldPoster pattern.
const SHOWCASE_VIDEOS = [
  // Blue-box caption variant — generated by our pipeline
  {
    src: cldVideo('v1780158596/demo-block-blue_t4pz1u', 720),
    poster: cldPoster('v1780158596/demo-block-blue_t4pz1u', 720),
  },
  // Middle slot — new pink-block captioned jewellery clip. Local for
  // now; replace with cldVideo/cldPoster once uploaded.
  {
    src: '/showcase/middle-pink.mp4',
    poster: '/showcase/middle-pink.jpg',
  },
  // Black-box caption variant — the original captioned hero
  {
    src: cldVideo('v1780158722/5b209243-f12b-4d4d-9365-6eac272fa36a_wopbcx', 720),
    poster: cldPoster('v1780158722/5b209243-f12b-4d4d-9365-6eac272fa36a_wopbcx', 720),
  },
];


// Responsive wall sizing. Total tile count drives how many <video> decoders
// the browser has to keep alive concurrently, which is the #1 source of
// jank on phones and mid-range laptops. We keep the unique-URL count at 6
// (so the network cost is identical across breakpoints) but scale the
// number of decoders down hard on smaller screens.
type WallLayout = { cols: number; perCol: number };
const LAYOUT_MOBILE: WallLayout = { cols: 3, perCol: 3 };   //  9 tiles
const LAYOUT_TABLET: WallLayout = { cols: 4, perCol: 4 };   // 16 tiles
const LAYOUT_DESKTOP: WallLayout = { cols: 5, perCol: 4 };  // 20 tiles

function pickLayout(width: number): WallLayout {
  if (width < 640) return LAYOUT_MOBILE;
  if (width < 1024) return LAYOUT_TABLET;
  return LAYOUT_DESKTOP;
}

function useWallLayout(): WallLayout {
  // SSR-safe: start with the *mobile* layout so phones never have to first
  // render the 20-tile desktop wall and then downshift — that flash of a
  // zoomed-out, over-populated grid is jarring and expensive on phones.
  // Desktops upgrade to the bigger wall on mount, which is cheap.
  const [layout, setLayout] = useState<WallLayout>(LAYOUT_MOBILE);
  useEffect(() => {
    const update = () => setLayout(pickLayout(window.innerWidth));
    update();
    window.addEventListener('resize', update);
    return () => window.removeEventListener('resize', update);
  }, []);
  return layout;
}

interface Tile {
  src: string;
  poster: string;
  label: string;
  live: boolean;
}

/* Reusable autoplay-when-visible video. Uses IntersectionObserver to
   pause whenever the element is fully off-screen, which is the single
   biggest perf win on this page — without it every <video> on the page
   keeps decoding even when scrolled past, which is what was making the
   site lag. Keep the API tiny so all other video components funnel
   through here. */
function AutoPlayVideo({
  src,
  poster,
  className,
  rootMargin = '200px',
}: {
  src: string;
  poster: string;
  className?: string;
  rootMargin?: string;
}) {
  const ref = useRef<HTMLVideoElement>(null);
  useEffect(() => {
    const v = ref.current;
    if (!v) return;
    // iOS Safari is notoriously strict about autoplay. There is a long-
    // standing React bug where the `muted` JSX prop occasionally doesn't
    // make it onto the DOM element as the `muted` attribute, which causes
    // iOS to refuse autoplay and show a play overlay. Force the property
    // on the element directly to guarantee it's muted before play().
    v.muted = true;
    v.defaultMuted = true;
    v.setAttribute('muted', '');
    v.setAttribute('playsinline', '');
    v.setAttribute('webkit-playsinline', '');
    const tryPlay = () => {
      v.play().catch(() => {});
    };
    tryPlay();
    v.addEventListener('loadedmetadata', tryPlay);
    v.addEventListener('canplay', tryPlay);

    let io: IntersectionObserver | undefined;
    if (typeof IntersectionObserver !== 'undefined') {
      io = new IntersectionObserver(
        ([entry]) => {
          if (entry.isIntersecting) tryPlay();
          else v.pause();
        },
        { rootMargin, threshold: 0 },
      );
      io.observe(v);
    }
    return () => {
      io?.disconnect();
      v.removeEventListener('loadedmetadata', tryPlay);
      v.removeEventListener('canplay', tryPlay);
    };
  }, [rootMargin]);
  return (
    <video
      ref={ref}
      src={src}
      poster={poster}
      autoPlay
      muted
      loop
      playsInline
      preload="auto"
      disablePictureInPicture
      className={className}
    />
  );
}

export function BlinkLanding() {
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 40);
    window.addEventListener('scroll', onScroll, { passive: true });
    onScroll();
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  // Preload the unique tile videos + posters as soon as the page mounts
  // so the wall hydrates from cache and plays instantly.
  useEffect(() => {
    const added: HTMLLinkElement[] = [];
    const head = document.head;
    for (const v of TILE_VIDEOS) {
      const lv = document.createElement('link');
      lv.rel = 'preload';
      lv.as = 'video';
      lv.href = v.src;
      lv.type = 'video/mp4';
      head.appendChild(lv);
      added.push(lv);

      const lp = document.createElement('link');
      lp.rel = 'preload';
      lp.as = 'image';
      lp.href = v.poster;
      head.appendChild(lp);
      added.push(lp);
    }
    // Also kick off a hidden fetch on the videos themselves — some
    // browsers ignore <link rel=preload as=video>, but fetch() always
    // primes the HTTP cache for the <video> elements below.
    const ctrl = new AbortController();
    for (const v of TILE_VIDEOS) {
      fetch(v.src, { signal: ctrl.signal, mode: 'no-cors', cache: 'force-cache' }).catch(() => {});
    }
    return () => {
      ctrl.abort();
      for (const el of added) {
        try { head.removeChild(el); } catch {}
      }
    };
  }, []);

  const layout = useWallLayout();

  // Tiles deterministically reuse the 6 real Cloudinary template videos.
  // Every tile sharing the same `src` pulls from the browser cache after
  // the first load, so the wall is effectively instant once the 6 videos
  // are fetched. Tile count varies by breakpoint (see `useWallLayout`).
  const tiles: Tile[] = useMemo(() => {
    const total = layout.cols * layout.perCol;
    return Array.from({ length: total }, (_, i) => {
      const v = TILE_VIDEOS[i % TILE_VIDEOS.length];
      return {
        src: v.src,
        poster: v.poster,
        label: v.label,
        // deterministic "live" dots — every 4th tile, but never the first
        live: i > 0 && i % 4 === 1,
      };
    });
  }, [layout.cols, layout.perCol]);

  return (
    <div className="font-body-blink bg-[#050608] text-white overflow-x-hidden">
      <Nav scrolled={scrolled} />
      <Hero tiles={tiles} layout={layout} />
      <Showcase />
      <FeatureBreakdown />
      <SpeedSection />
      <PricingSection />
      <Faq />
      <FinalCta />
      <Footer />
    </div>
  );
}

/* ============================================================
   PRICING SECTION — credit packs sourced from the backend (with
   a static fallback so the page renders even if the API is down).
   Buttons route logged-out visitors to /login?next=/pricing so
   they land directly on the in-app checkout after sign-in.
============================================================ */
function PricingSection() {
  const [packs, setPacks] = useState<CreditPack[]>(STATIC_PACK_FALLBACK);
  // `null` until the locale check runs client-side — important because
  // SSR + hydration would otherwise flash the wrong CTA copy.
  const [india, setIndia] = useState<boolean | null>(null);

  useEffect(() => {
    setIndia(isLikelyIndia());
  }, []);

  useEffect(() => {
    let mounted = true;
    fetchPublicPacks().then((p) => { if (mounted && p.length) setPacks(p); });
    return () => { mounted = false; };
  }, []);

  // While the geo-check pends, we render the India layout as the optimistic
  // default — it's the larger market and switching the CTA copy after
  // hydration is a non-visual change to most visitors.
  const isInternational = india === false;
  const mailtoSubject = encodeURIComponent('Early access — international credits');
  const mailtoBody = encodeURIComponent(
    "Hey Blink UGC team,\n\nI'd love to buy credits but I'm outside India. " +
    "Can you set me up with early access?\n\nThanks!"
  );
  const earlyAccessMailto =
    `mailto:${SUPPORT_EMAIL}?subject=${mailtoSubject}&body=${mailtoBody}`;

  return (
    <section
      id="pricing"
      className="relative z-[5] px-5 py-[110px]"
      style={{ background: 'linear-gradient(180deg, #0b0d12, #050608)' }}
    >
      <div className="mx-auto max-w-[1180px]">
        <div className="text-center mb-10 max-w-[820px] mx-auto">
          <span
            className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.2em] text-white/60 mb-5"
          >
            Pricing
          </span>
          <h2
            className="font-display-blink font-black"
            style={{ fontSize: 'clamp(30px, 4.6vw, 56px)', lineHeight: 1.02, letterSpacing: '-0.025em' }}
          >
            Buy <span className="blink-accent-text">credits</span>, never a subscription.
          </h2>
          <p className="mx-auto mt-5 max-w-[620px] text-[17px] leading-[1.6] text-white/60">
            5-second video = 50 credits. 10-second video = 100 credits. Bigger packs land
            at a per-credit discount. Credits never expire.
          </p>
        </div>

        <div className="mx-auto mb-10 max-w-[680px] rounded-[16px] border border-white/10 bg-white/[0.04] px-5 py-4 text-center text-[13.5px] leading-[1.55] text-white/80">
          <span className="font-semibold text-white">Not in India?</span>{' '}
          Mail us at{' '}
          <a
            href={earlyAccessMailto}
            className="text-white underline decoration-white/40 underline-offset-2 hover:decoration-white"
          >
            {SUPPORT_EMAIL}
          </a>{' '}
          to get special access.
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-[18px]">
          {packs.map((p) => {
            // Single currency for v1 — INR only. The USD path will light up
            // automatically the moment we flip the geo-gate after PayPal-via-Razorpay
            // verification clears.
            const priceMinor = p.price_paise;
            const major = Math.round(priceMinor / 100);
            const perCredit = priceMinor / 100 / p.credits;
            const perCreditLabel = `₹${perCredit.toFixed(2)}/credit`;
            const symbol = '₹';
            const locale = 'en-IN';
            const featured = p.id === 'creator';
            return (
              <div
                key={p.id}
                className={[
                  'relative rounded-[20px] p-6 flex flex-col transition-all duration-300 ease-out hover:-translate-y-1',
                  featured
                    ? 'border-transparent bg-gradient-to-b from-[#ff2e3f]/15 via-white/[0.02] to-white/[0.02] ring-1 ring-[#ff2e3f]/55'
                    : 'border border-white/10 bg-white/[0.03] hover:border-[rgba(77,130,255,0.45)]',
                ].join(' ')}
              >
                {featured && (
                  <div
                    className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full px-3 py-[3px] text-[10px] font-bold uppercase tracking-[1px] text-white"
                    style={{ background: 'linear-gradient(135deg,#ff2e3f,#e11d2b)' }}
                  >
                    Most popular
                  </div>
                )}
                <div className="text-[13px] uppercase tracking-[0.2em] text-white/45 mb-2">
                  {p.label}
                </div>
                <div className="flex items-baseline gap-2">
                  <div
                    className="font-display-blink font-black tabular-nums"
                    style={{ fontSize: 'clamp(34px, 3.4vw, 44px)', letterSpacing: '-0.02em', lineHeight: 1 }}
                  >
                    {`${symbol}${major.toLocaleString(locale)}`}
                  </div>
                </div>
                <div className="text-[12px] text-white/45 mt-2">
                  {p.credits.toLocaleString()} credits · {perCreditLabel}
                </div>

                <p className="mt-5 text-[13.5px] leading-[1.5] text-white/75 min-h-[42px]">
                  {p.blurb}
                </p>

                <ul className="mt-5 space-y-2 text-[13px] text-white/70 flex-1">
                  <LandingFeature>{Math.floor(p.credits / 50)} × 5-second videos</LandingFeature>
                  <LandingFeature>
                    {Math.floor(p.credits / 100)} × 10-second videos
                    {p.credits % 100 >= 50
                      ? ` + ${Math.floor((p.credits % 100) / 50)} × 5-second video`
                      : ''}
                  </LandingFeature>
                  <LandingFeature>Captions baked in</LandingFeature>
                  <LandingFeature>Credits never expire</LandingFeature>
                </ul>

                {isInternational ? (
                  <a
                    href={earlyAccessMailto}
                    className={[
                      'mt-6 inline-flex h-11 items-center justify-center gap-2 rounded-full text-[14px] font-semibold transition',
                      featured
                        ? 'bg-[#ff2e3f] text-white hover:bg-[#e11d2b] shadow-[0_10px_30px_rgba(225,29,43,0.35)]'
                        : 'bg-white text-[#080808] hover:bg-white/90',
                    ].join(' ')}
                  >
                    Mail for early access
                  </a>
                ) : (
                  <Link
                    href={`/login?mode=signup&next=${encodeURIComponent('/pricing')}`}
                    className={[
                      'mt-6 inline-flex h-11 items-center justify-center gap-2 rounded-full text-[14px] font-semibold transition',
                      featured
                        ? 'bg-[#ff2e3f] text-white hover:bg-[#e11d2b] shadow-[0_10px_30px_rgba(225,29,43,0.35)]'
                        : 'bg-white text-[#080808] hover:bg-white/90',
                    ].join(' ')}
                  >
                    Get {p.label}
                  </Link>
                )}
              </div>
            );
          })}
        </div>

        <p className="mt-8 text-center text-[12px] text-white/40">
          {isInternational
            ? 'International checkout (PayPal & cards) going live next week — email us above for early access.'
            : 'Secure checkout by Razorpay · UPI, cards, netbanking, wallets · One-time, no auto-renewal'}
        </p>
      </div>
    </section>
  );
}

function LandingFeature({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex items-start gap-2">
      <Check className="mt-[3px] h-3.5 w-3.5 shrink-0 text-emerald-400" />
      <span>{children}</span>
    </li>
  );
}

/* ============================================================
   PROMO BAR
============================================================ */
function PromoBar() {
  return (
    <div className="relative z-[60] flex flex-wrap items-center justify-center gap-2 px-3 py-[9px] text-center text-[12px] font-medium tracking-[0.2px] text-white sm:gap-3.5 sm:px-4 sm:text-[13px]"
         style={{ background: 'linear-gradient(90deg, #e11d2b, #ff2e3f)' }}>
      <span>
        <span aria-hidden>🔥</span>{' '}
        <span className="hidden sm:inline">Kling 3.0 Pro is <b className="font-bold">LIVE</b> — create your first AI ad now</span>
        <span className="sm:hidden">Create your first AI ad now</span>
      </span>
      <a
        href="#cta-main"
        className="whitespace-nowrap rounded-full bg-white px-3 py-[4px] text-[11px] font-bold text-[#0a0a0a] transition-transform duration-150 hover:-translate-y-0.5 sm:px-3.5 sm:py-[5px] sm:text-xs"
      >
        Try Now
      </a>
    </div>
  );
}

/* ============================================================
   NAV
============================================================ */
function Nav({ scrolled }: { scrolled: boolean }) {
  return (
    <nav
      className={[
        'fixed left-0 right-0 top-0 z-50 flex items-center justify-between',
        'transition-[background,backdrop-filter,border-color,margin-top,padding] duration-300 ease-out',
        scrolled
          ? 'mt-0 border-b border-white/10 bg-[rgba(5,6,8,0.72)] px-4 py-3 backdrop-blur-xl sm:px-9 sm:py-3.5'
          : 'mt-0 border-b border-transparent px-4 py-3 sm:px-9 sm:py-[18px]',
      ].join(' ')}
      style={scrolled ? { backdropFilter: 'blur(18px) saturate(140%)', WebkitBackdropFilter: 'blur(18px) saturate(140%)' } : undefined}
    >
      <Link href="/" className="flex items-center">
        <Image
          src="/brand/logo-combined.png"
          alt="Blink UGC"
          width={200}
          height={42}
          priority
          className="h-[28px] w-auto sm:h-[38px]"
        />
      </Link>

      <div className="flex items-center gap-[30px] text-[14.5px] font-medium max-[900px]:hidden">
        <NavLink href="#how">How it works</NavLink>
        <NavLink href="#pricing">Pricing</NavLink>
        <NavLink href="#faq">FAQ</NavLink>
      </div>

      <div className="flex items-center gap-3.5">
        <Link
          href="/login"
          className="hidden px-1.5 py-2.5 text-[14.5px] font-medium text-white transition-opacity hover:opacity-70 sm:inline-block"
        >
          Login
        </Link>
        <Link
          href="/login?mode=signup"
          className="rounded-full bg-white px-4 py-2 text-[13px] font-bold text-[#080808] transition-all duration-200 ease-out hover:-translate-y-0.5 hover:shadow-[0_12px_30px_rgba(255,255,255,0.18)] sm:px-[22px] sm:py-2.5 sm:text-[14.5px]"
        >
          Get Started
        </Link>
      </div>
    </nav>
  );
}

function NavLink({ href, children, caret }: { href: string; children: React.ReactNode; caret?: boolean }) {
  return (
    <a href={href} className="relative text-white/60 transition-colors hover:text-white">
      {children}
      {caret && <span className="ml-[5px] text-[9px] opacity-60">▾</span>}
    </a>
  );
}

/* ============================================================
   HERO
============================================================ */
function Hero({ tiles, layout }: { tiles: Tile[]; layout: WallLayout }) {
  return (
    <header
      className="relative flex min-h-screen flex-col items-center justify-center overflow-hidden px-4 pb-20 pt-[110px] text-center sm:px-5 sm:pt-[120px]"
    >
      <VideoWall tiles={tiles} layout={layout} />

      <div className="pointer-events-none absolute inset-0 z-[1] blink-hero-edges" />
      <div
        className="pointer-events-none absolute left-1/2 top-1/2 z-[2] -translate-x-1/2 -translate-y-1/2 rounded-[40px] blink-hero-frost"
        style={{ width: 'min(880px, 92vw)', height: 'min(560px, 72vh)' }}
      />
      <div className="pointer-events-none absolute inset-0 z-[1] blink-hero-vignette" />

      <div className="relative z-[5] max-w-[920px]">
        <span className="blink-rise mb-[26px] inline-flex items-center gap-2.5 rounded-full border border-white/10 bg-white/[0.07] px-4 py-[7px] text-[13px] font-semibold tracking-[0.5px] text-white backdrop-blur">
          <span className="h-[7px] w-[7px] rounded-full" style={{ background: '#ff2e3f', boxShadow: '0 0 10px #ff2e3f' }} />
          Powered by Kling 3.0 Pro
        </span>

        <h1
          className="font-display-blink font-black blink-rise"
          style={{
            fontSize: 'clamp(34px, 6vw, 76px)',
            lineHeight: 0.96,
            letterSpacing: '-0.03em',
            textShadow: '0 8px 50px rgba(0,0,0,0.7)',
            animationDelay: '0.06s',
          }}
        >
          The fastest way to create{' '}
          <span className="blink-accent-text">UGC&nbsp;videos</span>
        </h1>

        <p
          className="blink-rise mx-auto mt-[26px] max-w-[560px] font-normal leading-[1.55] text-white/60"
          style={{
            fontSize: 'clamp(15px, 1.9vw, 19px)',
            textShadow: '0 2px 16px rgba(0,0,0,0.7)',
            animationDelay: '0.14s',
          }}
        >
          <span className="font-semibold text-white">Write your script</span>
          <span className="mx-[7px] font-bold" style={{ color: '#4d82ff' }}>→</span>
          <span className="font-semibold text-white">Pick an avatar</span>
          <span className="mx-[7px] font-bold" style={{ color: '#4d82ff' }}>→</span>
          <span className="font-semibold text-white">Generate video</span>
        </p>

        <div
          id="cta-main"
          className="blink-rise mt-[30px] flex flex-wrap items-center justify-center gap-3 sm:mt-[38px] sm:gap-4"
          style={{ animationDelay: '0.22s' }}
        >
          <Link
            href="/login?mode=signup"
            className="blink-sheen relative overflow-hidden rounded-full border-none px-7 py-[14px] font-display-blink text-[15px] font-extrabold tracking-[0.2px] text-white transition-all duration-200 ease-out hover:-translate-y-[3px] hover:scale-[1.02] sm:px-[38px] sm:py-[18px] sm:text-[17px]"
            style={{
              background: 'linear-gradient(135deg, #ff2e3f, #e11d2b)',
              boxShadow: '0 14px 44px rgba(225,29,43,0.5), inset 0 1px 0 rgba(255,255,255,0.2)',
            }}
          >
            <span className="relative z-[2]">Create Your Ad →</span>
          </Link>
        </div>

      </div>

      <div
        className="blink-rise absolute bottom-[26px] left-1/2 z-[5] flex -translate-x-1/2 flex-col items-center gap-2 text-[11px] uppercase tracking-[2px] text-white/60"
        style={{ animationDelay: '0.5s' }}
      >
        <span>Scroll</span>
        <span
          className="blink-cue-bar h-[34px] w-px"
          style={{ background: 'linear-gradient(rgba(255,255,255,0.6), transparent)' }}
        />
      </div>
    </header>
  );
}

/* ============================================================
   VIDEO WALL
============================================================ */
function VideoWall({
  tiles,
  layout,
}: {
  tiles: Tile[];
  layout: WallLayout;
}) {
  // We use inline `gridTemplateColumns` instead of a Tailwind class because
  // `grid-cols-N` would require N to be statically known at build time and
  // we need to swap it at runtime per breakpoint.
  return (
    <div
      className="absolute z-0 grid gap-3.5"
      style={{
        inset: '-8%',
        transform: 'rotate(-4deg) scale(1.18)',
        transformOrigin: 'center',
        gridTemplateColumns: `repeat(${layout.cols}, minmax(0, 1fr))`,
      }}
      aria-hidden
    >
      {Array.from({ length: layout.cols }).map((_, c) => {
        const dir = c % 2 === 0 ? 'blink-col-up' : 'blink-col-down';
        const slow = c % 3 === 0 ? 'blink-slow' : '';
        // Rotate each column's tile slice by `c` so adjacent same-direction
        // columns (e.g. col 0 and col 2 on mobile) don't show the same
        // videos lined up side-by-side.
        const baseTiles = tiles.slice(c * layout.perCol, c * layout.perCol + layout.perCol);
        const shift = c % baseTiles.length;
        const colTiles = [...baseTiles.slice(shift), ...baseTiles.slice(0, shift)];
        // Negative animation-delay desynchronises the vertical scroll phase
        // so even-direction columns aren't moving in lockstep.
        const phaseDelay = `${-2.3 * c}s`;
        return (
          <div
            key={c}
            className={`flex flex-col gap-3.5 ${dir} ${slow}`}
            style={{ animationDelay: phaseDelay }}
          >
            {[...colTiles, ...colTiles].map((tile, i) => (
              <VTile key={`${c}-${i}`} tile={tile} />
            ))}
          </div>
        );
      })}
    </div>
  );
}

function VTile({ tile }: { tile: Tile }) {
  return (
    <div
      className="relative aspect-[9/16] shrink-0 overflow-hidden rounded-[14px] bg-[#11131a]"
      style={{ boxShadow: '0 18px 50px rgba(0,0,0,0.55)' }}
    >
      {tile.live && (
        <span
          className="blink-live-dot absolute left-[9px] top-[9px] z-[3] h-[7px] w-[7px] rounded-full"
          style={{ background: '#ff2e3f' }}
        />
      )}
      <AutoPlayVideo
        src={tile.src}
        poster={tile.poster}
        className="block h-full w-full object-cover"
      />
    </div>
  );
}

/* ============================================================
   HOW IT WORKS (new section)
============================================================ */
function HowItWorks() {
  const steps = [
    {
      n: '01',
      t: 'Write your script',
      d: 'Paste a hook or let our AI write one for you in your brand voice. Three variations in under 10 seconds.',
    },
    {
      n: '02',
      t: 'Pick an avatar',
      d: 'Choose from 200+ hyper-real creators — or generate a brand-new one from a single prompt.',
    },
    {
      n: '03',
      t: 'Generate & ship',
      d: 'Kling 3.0 Pro renders a 9:16 video with lip-synced voice and captions, ready for TikTok & Reels.',
    },
  ];

  return (
    <section
      id="how"
      className="relative z-[5] px-5 py-[110px] text-center"
      style={{ background: 'linear-gradient(180deg, #050608, #0b0d12)' }}
    >
      <h2
        className="mx-auto max-w-[780px] font-display-blink font-black"
        style={{ fontSize: 'clamp(30px, 4.6vw, 56px)', lineHeight: 1.02, letterSpacing: '-0.025em' }}
      >
        Three steps from blank page to <span style={{ color: '#ff2e3f' }}>scroll-stopping ad.</span>
      </h2>
      <p className="mx-auto mt-5 max-w-[560px] text-[17px] leading-[1.6] text-white/60">
        No studio, no crew, no shoot day. Just a fast feedback loop between you and the data.
      </p>

      <div className="mx-auto mt-16 grid max-w-[1080px] grid-cols-1 gap-[22px] md:grid-cols-3">
        {steps.map((s) => (
          <div
            key={s.n}
            className="relative rounded-[20px] border border-white/10 bg-white/[0.03] p-7 text-left transition-all duration-300 ease-out hover:-translate-y-2 hover:border-[rgba(77,130,255,0.5)]"
          >
            <div
              className="font-display-blink text-[44px] font-black leading-none"
              style={{
                background: 'linear-gradient(135deg, #4d82ff, #2563ff, #ff2e3f)',
                WebkitBackgroundClip: 'text',
                backgroundClip: 'text',
                color: 'transparent',
              }}
            >
              {s.n}
            </div>
            <h3 className="mt-4 font-display-blink text-[22px] font-bold">{s.t}</h3>
            <p className="mt-2 text-[15px] leading-[1.55] text-white/60">{s.d}</p>
          </div>
        ))}
      </div>
    </section>
  );
}

/* ============================================================
   FEATURE BREAKDOWN — 3 alternating cards with UI mockups
============================================================ */
function FeatureBreakdown() {
  const items: {
    kicker: number;
    title: string;
    desc: string;
    Mockup: () => JSX.Element;
    mockupRight: boolean;
  }[] = [
    {
      kicker: 0,
      title: 'Write or generate your script',
      desc: 'Enter your hook or let AI write three variations in your brand voice — in seconds.',
      Mockup: ScriptMockup,
      mockupRight: true,
    },
    {
      kicker: 1,
      title: 'Choose from a creator template',
      desc: 'Pick a hyper-real presenter from our template library — or generate a brand-new creator from a single prompt.',
      Mockup: ActorsMockup,
      mockupRight: false,
    },
    {
      kicker: 2,
      title: 'Add your product',
      desc: 'Drop in your product name, a few details, or a photo. Blink weaves it naturally into the script and the scene.',
      Mockup: ProductMockup,
      mockupRight: true,
    },
    {
      kicker: 3,
      title: 'Generate your video',
      desc: 'Combine creator, script, and product into a 9:16 lip-synced ad — ready for TikTok and Reels.',
      Mockup: VideoMockup,
      mockupRight: false,
    },
    {
      kicker: 4,
      title: 'Add captions, your way',
      desc: 'Burn in captions with one tap. Choose from 10 ready-made styles — bold, hype, clean, block, pink-pop and more.',
      Mockup: CaptionsMockup,
      mockupRight: true,
    },
  ];

  const totalSteps = items.length;

  return (
    <section
      id="how"
      className="relative z-[5] px-5 py-[110px] text-center"
      style={{ background: 'linear-gradient(180deg, #0b0d12, #050608)' }}
    >
      <h2
        className="mx-auto max-w-[860px] font-display-blink font-black"
        style={{ fontSize: 'clamp(30px, 4.6vw, 56px)', lineHeight: 1.02, letterSpacing: '-0.025em' }}
      >
        Create <span className="blink-accent-text">AI&nbsp;UGC</span> videos in minutes
      </h2>
      <p className="mx-auto mt-5 max-w-[560px] text-[17px] leading-[1.6] text-white/60">
        From idea to video in minutes — ready to use instantly.
      </p>

      <div className="mx-auto mt-12 max-w-[1120px] overflow-hidden rounded-[20px] border border-white/10 bg-white/[0.02] sm:mt-16">
        {items.map((it, rowIdx) => (
          <div
            key={it.kicker}
            className={[
              'grid grid-cols-1 md:grid-cols-2',
              rowIdx > 0 ? 'border-t border-white/10' : '',
            ].join(' ')}
          >
            <div className={`flex border-b border-white/10 md:border-b-0 ${it.mockupRight ? 'md:border-r md:border-white/10' : 'md:order-2'}`}>
              <FeatureTextCard kicker={it.kicker} total={totalSteps} title={it.title} desc={it.desc} />
            </div>
            <div className={`flex ${it.mockupRight ? '' : 'md:order-1 md:border-r md:border-white/10'}`}>
              <FeatureMockupCard>
                <it.Mockup />
              </FeatureMockupCard>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

function FeatureTextCard({ kicker, total, title, desc }: { kicker: number; total: number; title: string; desc: string }) {
  return (
    <div className="relative flex w-full min-h-[220px] flex-col bg-white/[0.03] p-6 text-left transition-colors duration-300 ease-out hover:bg-white/[0.05] sm:p-7 md:min-h-[340px]">
      <StepIndicator active={kicker} total={total} />
      <div className="mt-auto pt-8">
        <h3 className="font-display-blink text-[20px] font-bold leading-tight sm:text-[22px]">{title}</h3>
        <p className="mt-2 text-[14px] leading-[1.55] text-white/60 sm:text-[15px]">{desc}</p>
      </div>
    </div>
  );
}

function FeatureMockupCard({ children }: { children: React.ReactNode }) {
  return (
    <div
      className="relative flex w-full min-h-[260px] items-center justify-center overflow-hidden p-6 sm:p-8 md:min-h-[340px]"
      style={{
        background:
          'radial-gradient(circle at 30% 20%, rgba(77,130,255,0.10), transparent 55%), radial-gradient(circle at 80% 80%, rgba(255,46,63,0.08), transparent 55%), rgba(255,255,255,0.03)',
      }}
    >
      {children}
    </div>
  );
}

function StepIndicator({ active, total = 3, className = '' }: { active: number; total?: number; className?: string }) {
  return (
    <div className={`flex gap-1.5 ${className}`}>
      {Array.from({ length: total }, (_, i) => i).map((i) => (
        <span
          key={i}
          className="h-[3px] w-7 rounded-full"
          style={{ background: i === active ? '#4d82ff' : 'rgba(77,130,255,0.22)' }}
        />
      ))}
    </div>
  );
}

/* ----- Mockup 1: Script writer ----- */
function ScriptMockup() {
  return (
    <div className="w-full max-w-[420px]">
      <div
        className="rounded-2xl border border-white/10 bg-[#0a0b10] p-4 text-left"
        style={{ boxShadow: '0 28px 60px rgba(0,0,0,0.55), inset 0 1px 0 rgba(255,255,255,0.04)' }}
      >
        <div className="flex items-start justify-between gap-3">
          <span className="text-[14px] text-white/35">Write your script…</span>
          <span
            className="inline-flex shrink-0 items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold text-white"
            style={{ background: 'linear-gradient(135deg, #4d82ff, #7a4dff 60%, #ff2e3f)' }}
          >
            <Sparkles className="h-3 w-3" />
            AI Script writer
          </span>
        </div>

        <div className="h-14" />

        <div className="flex items-center justify-between">
          <span className="inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/[0.04] px-2.5 py-1 text-[11px] text-white/70">
            <Plus className="h-3 w-3" /> Credits <b className="text-white">6</b>
          </span>
          <span className="text-[11px] text-white/35">0 / 1000</span>
        </div>

        <div className="mt-3 flex flex-wrap items-center gap-1.5 border-t border-white/5 pt-3">
          <MockIconBtn>
            <Mic className="h-3.5 w-3.5" />
          </MockIconBtn>
          <MockChip>
            <Headphones className="h-3 w-3" />
            Talking Actors
            <ChevronDown className="h-3 w-3 opacity-60" />
          </MockChip>
          <MockChip>
            <Plus className="h-3 w-3" /> Add Actors
          </MockChip>
          <MockChip>
            <AudioLines className="h-3 w-3" /> Edit Voice
          </MockChip>
          <span className="ml-auto flex items-center gap-1.5">
            <MockIconBtn>
              <AudioWaveform className="h-3.5 w-3.5" />
            </MockIconBtn>
            <MockIconBtn accent>
              <ArrowUp className="h-3.5 w-3.5" />
            </MockIconBtn>
          </span>
        </div>
      </div>
    </div>
  );
}

function MockChip({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/[0.04] px-2.5 py-1 text-[11px] font-medium text-white/75">
      {children}
    </span>
  );
}

function MockIconBtn({ children, accent }: { children: React.ReactNode; accent?: boolean }) {
  return (
    <span
      className={
        accent
          ? 'grid h-7 w-7 place-items-center rounded-full bg-white text-[#080808]'
          : 'grid h-7 w-7 place-items-center rounded-full border border-white/10 bg-white/[0.05] text-white/75'
      }
    >
      {children}
    </span>
  );
}

/* ----- Mockup 2: Actor fan ----- */
function ActorsMockup() {
  // Reuse the same Cloudinary template posters as the hero wall so the
  // mockup feels real, not stocky. Poster only — no extra <video> decoders.
  // Switch the 2nd and 3rd pictures (indices 1 and 2).
  const base = TILE_VIDEOS.slice(0, 5);
  const cards = [base[0], base[2], base[1], base[3], base[4]];
  const names = ['Angela', 'Mike', 'Saman', 'Mila', 'Jason'];
  const layout = [
    { x: -120, y: 22, rot: -10, z: 1, scale: 0.9 },
    { x: -62, y: 6, rot: -5, z: 2, scale: 0.96 },
    { x: 0, y: -8, rot: 0, z: 3, scale: 1.08 },
    { x: 62, y: 6, rot: 5, z: 2, scale: 0.96 },
    { x: 120, y: 22, rot: 10, z: 1, scale: 0.9 },
  ];
  return (
    <div className="relative h-[220px] w-full max-w-[460px] scale-[0.78] sm:h-[260px] sm:scale-100">
      {cards.map((c, i) => {
        const p = layout[i];
        return (
          <div
            key={i}
            className="absolute left-1/2 top-1/2 aspect-[9/14] w-[120px] overflow-hidden rounded-[14px] border border-white/15 bg-[#11131a]"
            style={{
              transform: `translate(calc(-50% + ${p.x}px), calc(-50% + ${p.y}px)) rotate(${p.rot}deg) scale(${p.scale})`,
              zIndex: p.z,
              boxShadow: '0 22px 50px rgba(0,0,0,0.55)',
            }}
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={c.poster} alt="" className="h-full w-full object-cover" />
            {i === 2 && (
              <span className="absolute right-1.5 top-1.5 grid h-6 w-6 place-items-center rounded-full bg-black/55 text-white backdrop-blur">
                <Heart className="h-3 w-3 fill-white" />
              </span>
            )}
            <div className="absolute inset-x-1.5 bottom-1.5 flex items-center justify-between rounded-md bg-black/55 px-1.5 py-[3px] text-[10px] font-semibold text-white backdrop-blur">
              <span>{names[i]}</span>
              <span className="rounded-sm bg-white/20 px-1 text-[9px]">HD</span>
            </div>
          </div>
        );
      })}
    </div>
  );
}

/* ----- Mockup 3: Final video result ----- */
function VideoMockup() {
  // left, center, right
  const phoneIds = [
    'v1780166202/f0eeb973-9fec-4ac3-949a-43eef1379277_2_mlt9hy', // left
    'v1780320561/01-skincare-daylight-bold_o2q2d7',              // center
    'v1779194268/gym_wjiimf',                                    // right
  ];
  const c = phoneIds.map((id) => ({ src: cldVideo(id, 480), poster: cldPoster(id, 480) }));
  const layout = [
    { x: -95, y: 14, rot: -8, z: 1, scale: 0.92 },
    { x: 0, y: -12, rot: 0, z: 3, scale: 1.08 },
    { x: 95, y: 14, rot: 8, z: 1, scale: 0.92 },
  ];
  return (
    <div className="relative h-[240px] w-full max-w-[460px] scale-[0.8] sm:h-[300px] sm:scale-100">
      {c.map((v, i) => {
        const p = layout[i];
        return (
          <div
            key={i}
            className="absolute left-1/2 top-1/2 aspect-[9/19] w-[140px] overflow-hidden rounded-[22px] border-[3px] border-[#11131a] bg-[#11131a]"
            style={{
              transform: `translate(calc(-50% + ${p.x}px), calc(-50% + ${p.y}px)) rotate(${p.rot}deg) scale(${p.scale})`,
              zIndex: p.z,
              boxShadow: '0 26px 64px rgba(0,0,0,0.65)',
            }}
          >
            <AutoPlayVideo
              src={v.src}
              poster={v.poster}
              className="h-full w-full object-cover"
            />
            {i === 1 && (
              <span className="absolute left-2 top-2 rounded-full bg-black/65 px-2 py-[2px] text-[10px] font-semibold text-white backdrop-blur">
                01:48
              </span>
            )}
          </div>
        );
      })}
    </div>
  );
}

/* ----- Mockup 3: Add your product ----- */
function ProductMockup() {
  return (
    <div className="w-full max-w-[420px]">
      <div
        className="rounded-2xl border border-white/10 bg-[#0a0b10] p-4 text-left"
        style={{ boxShadow: '0 28px 60px rgba(0,0,0,0.55), inset 0 1px 0 rgba(255,255,255,0.04)' }}
      >
        <div className="flex items-center gap-3">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="https://res.cloudinary.com/dgx0o3xfx/image/upload/f_auto,q_auto,w_120/v1780344460/download_ljd2qd.webp"
            alt=""
            className="h-14 w-14 shrink-0 rounded-xl border border-white/10 object-cover"
          />
          <div className="min-w-0 flex-1">
            <div className="text-[10px] uppercase tracking-[0.18em] text-white/35">Product name</div>
            <div className="mt-1 truncate text-[14px] font-semibold text-white">Diamond Tops</div>
          </div>
        </div>

        <div className="mt-4 rounded-xl border border-white/10 bg-white/[0.03] p-3">
          <div className="text-[10px] uppercase tracking-[0.18em] text-white/35">Details</div>
          <p className="mt-1.5 text-[12.5px] leading-[1.5] text-white/60">
            Brilliant-cut diamond studs set in 18k gold. Everyday sparkle — hypoallergenic, certified, lifetime warranty.
          </p>
        </div>

        <div className="mt-3 flex flex-wrap items-center gap-1.5">
          <MockChip>
            <Plus className="h-3 w-3" /> Add photo
          </MockChip>
          <MockChip>
            <Plus className="h-3 w-3" /> Paste product URL
          </MockChip>
          <span className="ml-auto inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold text-white"
                style={{ background: 'linear-gradient(135deg, #4d82ff, #7a4dff 60%, #ff2e3f)' }}>
            <Check className="h-3 w-3" /> Linked to script
          </span>
        </div>
      </div>
    </div>
  );
}

/* ----- Mockup 5: Caption presets ----- */
function CaptionsMockup() {
  const styles: { label: string; fill: string; box?: string; outline?: boolean }[] = [
    { label: 'Bold', fill: '#ffffff', outline: true },
    { label: 'Hype', fill: '#ffffff', outline: true },
    { label: 'Yellow', fill: '#facc15', outline: true },
    { label: 'Block Blue', fill: '#ffffff', box: '#3b82f6' },
    { label: 'Pink Pop', fill: '#ffffff', box: '#ec4899' },
    { label: 'Block Black', fill: '#ffffff', box: '#000000' },
  ];
  return (
    <div className="w-full max-w-[420px]">
      <div
        className="rounded-2xl border border-white/10 bg-[#0a0b10] p-4 text-left"
        style={{ boxShadow: '0 28px 60px rgba(0,0,0,0.55), inset 0 1px 0 rgba(255,255,255,0.04)' }}
      >
        <div className="flex items-center justify-between">
          <span className="text-[12px] font-semibold text-white">Caption style</span>
          <span className="text-[11px] text-white/35">10 presets</span>
        </div>
        <div className="mt-3 grid grid-cols-3 gap-2">
          {styles.map((s, i) => (
            <div
              key={s.label}
              className={[
                'flex h-12 items-center justify-center rounded-lg border text-center text-[12px] font-black uppercase',
                i === 3 ? 'border-[#4d82ff] ring-1 ring-[#4d82ff]/60' : 'border-white/10',
              ].join(' ')}
              style={{ background: 'rgba(255,255,255,0.03)' }}
            >
              <span
                style={{
                  color: s.fill,
                  background: s.box,
                  padding: s.box ? '2px 5px' : undefined,
                  borderRadius: s.box ? 3 : undefined,
                  textShadow: s.outline && !s.box ? '0 1px 0 #000, 0 0 2px #000' : undefined,
                }}
              >
                {s.label.split(' ')[0]}
              </span>
            </div>
          ))}
        </div>
        <div className="mt-3 flex items-center gap-1.5 border-t border-white/5 pt-3">
          <MockChip>Auto-timed</MockChip>
          <MockChip>Burned in</MockChip>
          <span className="ml-auto inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold text-white"
                style={{ background: 'linear-gradient(135deg, #4d82ff, #7a4dff 60%, #ff2e3f)' }}>
            <Check className="h-3 w-3" /> Applied
          </span>
        </div>
      </div>
    </div>
  );
}

/* ============================================================
   SHOWCASE (cards w/ live video thumbs)
============================================================ */
function Showcase() {
  const cards = [
    {
      t: 'Hyper-real avatars',
      d: 'Diverse, lifelike presenters that look filmed on a phone — not rendered.',
      b: 'NEW',
      video: SHOWCASE_VIDEOS[0],
    },
    {
      t: 'Script → video, fast',
      d: 'Make your creator do anything with just a prompt.',
      b: 'FAST',
      video: SHOWCASE_VIDEOS[1],
    },
    {
      t: 'Built for ads',
      d: '9:16 native, captions baked in, ready to upload straight to TikTok & Reels.',
      b: 'ADS',
      video: SHOWCASE_VIDEOS[2],
    },
  ];

  return (
    <section
      id="features"
      className="relative z-[5] px-5 py-[110px] pb-[130px] text-center"
      style={{ background: 'linear-gradient(180deg, #050608, #0b0d12)' }}
    >
      <h2
        id="showcase"
        className="mx-auto max-w-[780px] font-display-blink font-black"
        style={{ fontSize: 'clamp(30px, 4.6vw, 56px)', lineHeight: 1.02, letterSpacing: '-0.025em' }}
      >
        One amazing video is all it takes to <span style={{ color: '#ff2e3f' }}>sell.</span>
      </h2>
      <p className="mx-auto mt-5 max-w-[560px] text-[17px] leading-[1.6] text-white/60">
        Generate hyper-realistic UGC ads in seconds. Real-looking avatars, real emotion, real conversions —
        at a fraction of the cost of a creator.
      </p>

      <div className="mx-auto mt-16 grid max-w-[1080px] grid-cols-1 gap-[22px] md:grid-cols-3">
        {cards.map((c) => (
          <div
            key={c.t}
            className="relative overflow-hidden rounded-[20px] border border-white/10 bg-white/[0.03] text-left transition-all duration-300 ease-out hover:-translate-y-2 hover:border-[rgba(77,130,255,0.5)]"
          >
            <div className="absolute right-3 top-3 z-[3] rounded-full border border-white/10 bg-black/60 px-3 py-[5px] text-[11px] font-bold tracking-[0.5px] backdrop-blur">
              {c.b}
            </div>
            {/* 9:16 matches our source videos' aspect exactly, so
                object-cover doesn't crop any frame edges. */}
            <div className="relative aspect-[9/16] overflow-hidden">
              <ShowcaseVideo src={c.video.src} poster={c.video.poster} />
            </div>
            <div className="p-[22px]">
              <h3 className="font-display-blink text-[19px] font-bold">{c.t}</h3>
              <p className="mt-2 text-[14.5px] leading-[1.55] text-white/60">{c.d}</p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

function ShowcaseVideo({ src, poster }: { src: string; poster: string }) {
  return (
    <AutoPlayVideo
      src={src}
      poster={poster}
      className="block h-full w-full object-cover"
    />
  );
}

/* ============================================================
   SPEED SECTION — replaces the old testimonials/stats blocks
============================================================ */
function SpeedSection() {
  const beats = [
    {
      time: 'Cast',
      title: 'Creator templates',
      desc: 'Choose a hyper-real presenter from our creator-template library — or generate a brand-new one from a single prompt.',
    },
    {
      time: '10',
      title: 'Caption presets',
      desc: 'Ten ready-made caption styles — bold, hype, clean, yellow, block, pink-pop and more — burned in and auto-timed to your script.',
    },
    {
      time: '9:16',
      title: 'Post-ready exports',
      desc: 'Every ad renders native vertical with captions baked in — upload straight to TikTok, Reels and Shorts.',
    },
  ];

  return (
    <section className="relative z-[5] px-5 py-[110px]" style={{ background: '#050608' }}>
      <h2
        className="mx-auto max-w-[820px] text-center font-display-blink font-black"
        style={{ fontSize: 'clamp(30px, 4.6vw, 56px)', lineHeight: 1.02, letterSpacing: '-0.025em' }}
      >
        Generate at the <span className="blink-accent-text">speed of thought.</span>
      </h2>
      <p className="mx-auto mt-5 max-w-[600px] text-center text-[17px] leading-[1.6] text-white/60">
        Type your idea, pick a template, and watch the ad come together — then iterate again,
        and again, until the data picks a winner.
      </p>

      <div className="mx-auto mt-16 grid max-w-[1080px] grid-cols-1 gap-[22px] md:grid-cols-3">
        {beats.map((b) => (
          <div
            key={b.title}
            className="relative rounded-[20px] border border-white/10 bg-white/[0.03] p-7 text-left transition-all duration-300 ease-out hover:-translate-y-2 hover:border-[rgba(77,130,255,0.5)]"
          >
            <div
              className="font-display-blink font-black leading-none"
              style={{
                fontSize: 'clamp(36px, 4.5vw, 48px)',
                background: 'linear-gradient(135deg, #4d82ff, #2563ff, #ff2e3f)',
                WebkitBackgroundClip: 'text',
                backgroundClip: 'text',
                color: 'transparent',
              }}
            >
              {b.time}
            </div>
            <h3 className="mt-4 font-display-blink text-[22px] font-bold">{b.title}</h3>
            <p className="mt-2 text-[15px] leading-[1.55] text-white/60">{b.desc}</p>
          </div>
        ))}
      </div>
    </section>
  );
}

/* ============================================================
   FAQ (new section)
============================================================ */
function Faq() {
  const items = [
    {
      q: 'What model powers Blink UGC?',
      a: "Every video is rendered on Kling 3.0 Pro — the latest state-of-the-art video model — with ElevenLabs voices on top for lip-synced dialogue.",
    },
    {
      q: 'How long does a video take to generate?',
      a: 'Just a short wait for a 9:16 ad. You can queue ten variations and let them all render in parallel.',
    },
    {
      q: 'Can I bring my own creator?',
      a: 'Yes. Generate a brand-new AI creator from a single prompt, or promote any generation to a reusable template.',
    },
    {
      q: 'Where do I post the videos?',
      a: 'Every ad is 9:16 native with baked-in captions, ready to upload directly to TikTok, Reels, Shorts, and Meta ads.',
    },
  ];
  return (
    <section id="faq" className="relative z-[5] px-5 py-[110px]" style={{ background: 'linear-gradient(180deg, #050608, #0b0d12)' }}>
      <h2
        className="mx-auto max-w-[780px] text-center font-display-blink font-black"
        style={{ fontSize: 'clamp(30px, 4.6vw, 56px)', lineHeight: 1.02, letterSpacing: '-0.025em' }}
      >
        Questions, <span style={{ color: '#ff2e3f' }}>answered.</span>
      </h2>
      <div className="mx-auto mt-12 max-w-[820px] divide-y divide-white/10 overflow-hidden rounded-[20px] border border-white/10 bg-white/[0.03]">
        {items.map((it) => (
          <FaqItem key={it.q} q={it.q} a={it.a} />
        ))}
      </div>
    </section>
  );
}

function FaqItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  return (
    <div>
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center justify-between gap-4 px-7 py-6 text-left transition-colors hover:bg-white/[0.02]"
      >
        <span className="font-display-blink text-[17px] font-semibold">{q}</span>
        <span
          className="grid h-7 w-7 place-items-center rounded-full border border-white/15 text-[13px] transition-transform duration-300"
          style={{ transform: open ? 'rotate(45deg)' : 'rotate(0)' }}
          aria-hidden
        >
          +
        </span>
      </button>
      <div
        ref={ref}
        className="overflow-hidden transition-[max-height,opacity] duration-300 ease-out"
        style={{
          maxHeight: open ? (ref.current?.scrollHeight ?? 200) : 0,
          opacity: open ? 1 : 0,
        }}
      >
        <p className="px-7 pb-6 text-[15px] leading-[1.65] text-white/65">{a}</p>
      </div>
    </div>
  );
}

/* ============================================================
   FINAL CTA
============================================================ */
function FinalCta() {
  return (
    <section
      id="get-started"
      className="relative z-[5] overflow-hidden px-5 py-[120px] text-center"
      style={{ background: 'radial-gradient(circle at 50% 0%, rgba(37,99,255,0.18), transparent 55%), #050608' }}
    >
      <h2
        className="font-display-blink font-black"
        style={{ fontSize: 'clamp(34px, 5.5vw, 68px)', letterSpacing: '-0.03em', lineHeight: 1 }}
      >
        Make your first ad <span style={{ color: '#ff2e3f' }}>today.</span>
      </h2>
      <p className="mx-auto mt-[22px] max-w-[480px] text-[17px] text-white/60">
        Stop guessing what converts. Generate ten variations before lunch and let the data decide.
      </p>
      <div className="mt-9 flex flex-wrap items-center justify-center gap-3 sm:gap-4">
        <Link
          href="/login?mode=signup"
          className="blink-sheen relative overflow-hidden rounded-full px-7 py-[14px] font-display-blink text-[15px] font-extrabold text-white transition-all duration-200 ease-out hover:-translate-y-[3px] hover:scale-[1.02] sm:px-[38px] sm:py-[18px] sm:text-[17px]"
          style={{
            background: 'linear-gradient(135deg, #ff2e3f, #e11d2b)',
            boxShadow: '0 14px 44px rgba(225,29,43,0.5), inset 0 1px 0 rgba(255,255,255,0.2)',
          }}
        >
          <span className="relative z-[2]">Create Your Ad →</span>
        </Link>
        <a
          href="#showcase"
          className="inline-flex items-center gap-2.5 rounded-full border border-white/[0.18] bg-white/[0.08] px-6 py-[14px] text-[14px] font-semibold text-white backdrop-blur transition-all duration-200 hover:-translate-y-0.5 hover:bg-white/[0.14] sm:px-[30px] sm:py-[18px] sm:text-[16px]"
        >
          <span className="grid h-[22px] w-[22px] place-items-center rounded-full bg-white text-[10px] text-[#080808] sm:h-[26px] sm:w-[26px] sm:text-[11px]">▶</span>
          See examples
        </a>
      </div>
    </section>
  );
}

/* ============================================================
   FOOTER
============================================================ */
function Footer() {
  return (
    <footer className="relative z-[5] flex flex-col items-center gap-5 border-t border-white/10 bg-[#050608] px-5 py-[28px] text-center text-[12px] text-white/60 sm:flex-row sm:flex-wrap sm:justify-between sm:gap-4 sm:px-9 sm:py-[38px] sm:text-left sm:text-[13px]">
      <div className="flex items-center">
        <Image
          src="/brand/logo-combined.png"
          alt="Blink UGC"
          width={150}
          height={68}
          className="h-[28px] w-auto sm:h-[34px]"
        />
      </div>
      <div className="flex items-center gap-5">
        <a href="/privacy" className="transition-colors hover:text-white">Privacy</a>
        <a href="/terms" className="transition-colors hover:text-white">Terms</a>
        <a href="mailto:hi@blinkugc.com" className="transition-colors hover:text-white">Contact</a>
      </div>
      <div>© {new Date().getFullYear()} Blink UGC. The fastest way to create UGC videos.</div>
    </footer>
  );
}
