import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — Blinkugc',
  description:
    'The terms that govern your use of the Blinkugc app and related services.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black text-white px-6 py-16 md:py-24">
      <article className="mx-auto max-w-3xl">
        <Link
          href="/"
          className="text-sm text-white/60 hover:text-white transition"
        >
          ← Back to Blinkugc
        </Link>

        <h1 className="mt-8 text-4xl md:text-5xl font-semibold tracking-tight">
          Terms of Service
        </h1>
        <p className="mt-3 text-sm text-white/50">Last updated: 29 May 2026</p>

        <div className="mt-12 space-y-10 text-white/80 leading-relaxed">
          <p>
            These Terms of Service (&ldquo;Terms&rdquo;) govern your use of the
            Blinkugc iOS application, website, and related services (the
            &ldquo;Service&rdquo;). By using the Service you agree to these
            Terms.
          </p>

          <section>
            <h2 className="text-2xl font-semibold text-white">1. Eligibility</h2>
            <p className="mt-4">
              You must be at least 13 years old (or the minimum age of digital
              consent in your country, whichever is higher) to use Blinkugc. By
              using the Service you represent that you meet this requirement.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              2. Your Account
            </h2>
            <p className="mt-4">
              You are responsible for the activity on your account and for
              keeping your sign-in credentials secure. You may delete your
              account at any time from inside the app (sidebar → profile →{' '}
              <strong>Delete account</strong>).
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">3. Your Content</h2>
            <p className="mt-4">
              You retain ownership of the prompts, photos, and other inputs you
              provide (&ldquo;Inputs&rdquo;) and the videos, images, and audio
              that the Service generates from those Inputs
              (&ldquo;Outputs&rdquo;). You grant us a worldwide, non-exclusive,
              royalty-free license to host, store, transmit, and process your
              Inputs and Outputs solely to operate and improve the Service.
            </p>
            <p className="mt-4">
              You represent that you have the right to use any photo, voice,
              brand, product, or other material you upload, and that your use
              does not infringe anyone else&rsquo;s rights.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              4. Acceptable Use
            </h2>
            <p className="mt-4">You agree not to use the Service to:</p>
            <ul className="mt-4 list-disc pl-6 space-y-2">
              <li>
                Generate content that depicts a real person without their
                consent, including non-consensual deepfakes.
              </li>
              <li>
                Generate content that sexually exploits minors or any other
                content prohibited by law.
              </li>
              <li>
                Generate content that harasses, threatens, defames, or violates
                the rights of others.
              </li>
              <li>
                Impersonate any person or entity, or misrepresent your
                affiliation with any person or entity.
              </li>
              <li>
                Reverse-engineer, decompile, or attempt to extract source code
                from the Service.
              </li>
              <li>
                Use the Service to build a competing product, or to scrape or
                harvest data from the Service.
              </li>
              <li>
                Use the Service in a way that violates any applicable law or
                the rules of a third-party platform on which you publish your
                Outputs.
              </li>
            </ul>
            <p className="mt-4">
              We may suspend or terminate your account if you violate these
              rules.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              5. AI-Generated Content Disclaimer
            </h2>
            <p className="mt-4">
              Outputs are generated by machine-learning models and may be
              inaccurate, biased, or unsuitable for your purpose. You are
              responsible for reviewing Outputs before publishing them and for
              complying with any disclosure rules (for example, the FTC&rsquo;s
              endorsement guidelines or platform-specific AI-content disclosure
              requirements).
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              6. Subscriptions and Payments
            </h2>
            <p className="mt-4">
              If we offer paid plans, the price, billing period, and renewal
              terms will be shown to you in the App Store before purchase.
              Subscriptions auto-renew through your Apple ID unless you cancel
              at least 24 hours before the end of the current period. You can
              manage subscriptions in your Apple ID settings. Refunds are
              handled by Apple.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">7. Termination</h2>
            <p className="mt-4">
              You may stop using the Service at any time and delete your
              account from inside the app. We may suspend or terminate your
              access if you violate these Terms or if we are required to do so
              by law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">8. Disclaimers</h2>
            <p className="mt-4">
              The Service is provided &ldquo;as is&rdquo; and &ldquo;as
              available&rdquo;. To the maximum extent permitted by law, we
              disclaim all warranties, including merchantability, fitness for a
              particular purpose, and non-infringement.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              9. Limitation of Liability
            </h2>
            <p className="mt-4">
              To the maximum extent permitted by law, in no event will our
              aggregate liability exceed the greater of (a) the amount you paid
              us for the Service in the 12 months preceding the claim and (b)
              USD $50. We are not liable for indirect, incidental,
              consequential, special, or punitive damages.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              10. Changes to the Service or Terms
            </h2>
            <p className="mt-4">
              We may modify or discontinue the Service, or update these Terms,
              at any time. Material changes will be posted in the app or on our
              website with an updated &ldquo;Last updated&rdquo; date.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              11. Governing Law
            </h2>
            <p className="mt-4">
              These Terms are governed by the laws of India, without regard to
              its conflict-of-law principles. Any dispute arising out of or in
              connection with these Terms shall be subject to the exclusive
              jurisdiction of the courts in New Delhi, India.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">12. Contact</h2>
            <p className="mt-4">
              Questions about these Terms? Email{' '}
              <a
                href="mailto:support@blinkugc.com"
                className="text-white underline"
              >
                support@blinkugc.com
              </a>
              .
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-white/10 text-sm text-white/40 flex gap-6">
          <Link href="/" className="hover:text-white transition">
            Home
          </Link>
          <Link href="/privacy" className="hover:text-white transition">
            Privacy Policy
          </Link>
        </div>
      </article>
    </main>
  );
}
